---
title: "Data_visualization"
output: pdf_document
---

# Ovules per family, **Convolvulaceae is constant 4 or 6**

```{r,message=FALSE, warning=FALSE, echo=FALSE, cache=FALSE, fig.height=3}
#load libraries

library(ggplot2)
library(Hmisc)
library(Formula)
#load data

par(mfrow=c(2,1))

d<-read.csv("Data/Ovules.csv", sep=";")

colnames(d)[1]<-"C. annuum"
colnames(d)[2]<-"S. lycopersicum"
colnames(d)[3]<-"S. melongera"
colnames(d)[4]<-"P. integrifolia"
colnames(d)[5]<-"B. oleracea"
colnames(d)[6]<-"B. rapa"
colnames(d)[7]<-"E. sativa"
colnames(d)[8]<-"S. alba"


#Reorganise data
d <- stack(d)
#Naming columns
colnames(d)[1]<-"ovules"
colnames(d)[2]<-"species"



#subset per family (solanaceae, brassicaceae, convolvulaceae)
solanaceae<-subset(d)[1:60,]
brassicaceae<-subset(d)[61:120,]

# OVULES SOLANACEAE
p <- ggplot(solanaceae, aes(x = reorder(species, ovules, FUN = median), y = ovules)) +   geom_boxplot()+
labs(title="Solanaceae",x="", y = "Ovules")+
theme(plot.title = element_text(hjust = 0.5))

p + stat_summary(fun.y=mean, geom="point", shape="*", size=5, colour="black")

# OVULES BRASSICACEAE

p <- ggplot(brassicaceae, aes(x = reorder(species, ovules, FUN = median), y = ovules)) +   geom_boxplot()+
  labs(title="Brassicaceae",x="", y = "Ovules")+
  theme(plot.title = element_text(hjust = 0.5))

p + stat_summary(fun.y=mean, geom="point", shape="*", size=5, colour="black")


```


#Pollen per anther, just one Convolvulaceae at the moment
```{r,message=FALSE, warning=FALSE, echo=FALSE, cache=FALSE, fig.height=3}
library(ggplot2)
library(Hmisc)
library(Formula)


p <- read.csv("data/Pollen.csv", sep = ";")

#Deleting extra row (21)
p <-p[-21,]

#boxplot(p)
#Reorganize data for ggplot
p<-stack(p)
#colnames
colnames(p)[1]<-"pollen"
colnames(p)[2]<-"species"

all<-p
solanaceae<-subset(p)[1:100,]
brassicaceae<- subset(p)[101:180,]

#Solanaceae

p <- ggplot(solanaceae, aes(x = reorder(species, pollen, FUN = median), y = pollen)) +   geom_boxplot()+
  labs(title="Solanaceae",x="", y = "pollen")+
  theme(plot.title = element_text(hjust = 0.5))

p + stat_summary(fun.y=mean, geom="point", shape="*", size=5, colour="black")


#Brassicaceae

p <- ggplot(brassicaceae, aes(x = reorder(species, pollen, FUN = median), y = pollen)) +   geom_boxplot()+
  labs(title="Brassicaceae",x="", y = "pollen")+
  theme(plot.title = element_text(hjust = 0.5))

p + stat_summary(fun.y=mean, geom="point", shape="*", size=5, colour="black")

#all

p <- ggplot(all, aes(x = reorder(species, pollen, FUN = median), y = pollen)) +   geom_boxplot()+
  labs(title="All species",x="", y = "pollen")+
  theme(plot.title = element_text(hjust = 0.5))

p + stat_summary(fun.y=mean, geom="point", shape="*", size=5, colour="black")

```

