---
title: "Untitled"
output: github_document
---
Other idea based on the paper of Aizen 2007:

He explains seed set in this way. O total number of ovules, d fraction of ovules that become seed set, b proportion of pollen grains that reach ovules, p number of pollen grains.

$S=dO(1-e^bp)$

$S=dO(1-e^bp(HpEffect))$

but this Hp effect maybe can be divided at the same time in the interaction between recipient-donor with the main traits that drive the effect. IB: maybe just a weighting factor 0-1 depending on trait matching? If effect of hetero is 0, it cancells out the term, if is maximum, it *1

Moreover, this should consider quantity of hp. lINEAR EFFECT? How to model this maybe talk with nacho. IB: In the absence of data you can try linearity, but also a sigmoidal.

IB: Cool! se also Morris et al 2010 Ecology on how to add to AIzen curve, the effects of a second curve describing the negative effect of hetero. Morris apporach is mathematically more robust if you can model the second curve of hp effects.

I also think you should use this for another paper and look into Morales -Castilla TREE paper inferring interactions. I can see a similar idea where you use a set of matrix you can multiply. 
1) A matrix of plant-plant pollinator influence ( a lo carvalehire 2014). This tells you which plants may get exposed to hp pollen from empirical plant pollinator networks
2) you matrix of plant plant ht effect (0-1) or a proxy based on phylogeny of trait similarity. This is also easy to quantify.
3) A vector of sensitive recipient traits.
 to create the probability of ht effects. I really like this ideas to link to community ecology.
