---
title: ""
output:
  pdf_document: default
  html_document: default
---
```{r, echo=FALSE, message=FALSE, warning=FALSE,cache=FALSE,fig.height=9,fig.width=7}
par(mar=c(30,13,2,4),xpd=F)
data_percentage <-readRDS("Rmd/Data/per.RData")
data_percentage=as.matrix(data_percentage)
coul = c("#999999","#779799")
barplot(data_percentage,hor=T, xlim=c(-1,100),ylim=c(-2,5),width = 0.5,col=coul ,space=0.5, border="white",srt=80,las=1,cex.axis=1,cex.names=1,names=c("Brassicaceae-Convolvulaceae",
 "Brassicaceae-Solanaceae","Convolvulaceae-Brassicaceae","Convolvulaceae-Solanaceae","Solanaceae-Convolvulaceae","Solanaceae-Brassicaceae"))
legend(-5,-0.5,legend=c("Recipient","Donor"),bty="n",fill = coul)
abline(v=50,col="black")

#lines(c(0,10),50,col="red")
```
\newpage
```{r, echo=FALSE, message=FALSE, warning=FALSE,cache=FALSE,fig.height=9,fig.width=7}
par(mar=c(30,13,2,4),xpd=F)
ratio_bra <-readRDS("Rmd/Data/ratio_bra.RData")
barplot(ratio_bra,hor=T, xlim=c(-1,100),ylim=c(-2,7),width = 0.5,col=coul ,space=0.5,border="white",srt=80,las=1,cex.axis=1,cex.names=1,font=3,names=c("E. sativa-I. purpurea",
  "B. oleracea-I. purpurea","B. rapa-I. purpurea","S. alba-I. aquatica", "S. alba-S. melongena", "E. sativa-P. integrifolia", "B. rapa-S. lycopersicum", "B. oleracea-C. annuum"))
abline(v=50,col="black")
legend(-1,-0.1,legend=c("Recipient","Donor"),bty="n",fill = coul)

```

\newpage
```{r, echo=FALSE, message=FALSE, warning=FALSE,cache=FALSE,fig.height=9,fig.width=7}
par(mar=c(30,13,2,4),xpd=F)
ratio_sol <-readRDS("Rmd/Data/ratio_sol.RData")
barplot(ratio_sol,hor=T, xlim=c(-1,100),ylim=c(-2,7),width = 0.5,col=coul ,space=0.5,border="white",srt=80,las=1,cex.axis=1,cex.names=1,font=3,names=c("C. annuum-I. purpurea", "S. melongena-I. aquatica", "P. integrifolia-I. aquatica", "S. lycopersicum-I aquatica","S. melongena-E. sativa", "P. integrifolia-E. sativa", "C. annuum-S. alba", "S. lycopersicum-B. rapa"))
abline(v=50,col="black")
legend(-1,-0.1,legend=c("Recipient","Donor"),bty="n",fill = coul)

```
\newpage
```{r, echo=FALSE, message=FALSE, warning=FALSE,cache=FALSE,fig.height=9,fig.width=7}
par(mar=c(30,13,2,4),xpd=F)
ratio_con <-readRDS("Rmd/Data/ratio_con.RData")
barplot(ratio_con,hor=T, xlim=c(-1,100),ylim=c(-2,5),width = 0.5,col=coul ,space=0.5,border="white",srt=80,las=1,cex.axis=1,cex.names=1,font=3,names=c("I. purpurea-S. melongena","I. aquatica-C. annuum","I. purpurea-E. sativa","I. aquatica-S. alba"))
abline(v=50,col="black")
legend(-1,-0.5,legend=c("Recipient","Donor"),bty="n",fill = coul)

```
\newpage
```{r, echo=FALSE, message=FALSE, warning=FALSE,cache=FALSE,fig.height=9,fig.width=7}
par(mar=c(2,13,2,4),xpd=F)
par(mfrow=c(3,1))
ratio_sol <-readRDS("Rmd/Data/ratio_sol.RData")
barplot(ratio_sol,hor=T, xlim=c(-1,100),ylim=c(-2,7),width = 0.5,col=coul ,space=0.5,border="white",srt=80,las=1,cex.axis=1,cex.names=1,font=3,names=c("C. annuum-I. purpurea", "S. melongena-I. aquatica", "P. integrifolia-I. aquatica", "S. lycopersicum-I aquatica","S. melongena-E. sativa", "P. integrifolia-E. sativa", "C. annuum-S. alba", "S. lycopersicum-B. rapa"))
abline(v=50,col="black")
legend(-1,-0.1,legend=c("Recipient","Donor"),bty="n",fill = coul)
text(8.3,6.8,"A) Brassicaceae")
ratio_con <-readRDS("Rmd/Data/ratio_con.RData")
barplot(ratio_con,hor=T, xlim=c(-1,100),ylim=c(-2,5),width = 0.5,col=coul ,space=0.5,border="white",srt=80,las=1,cex.axis=1,cex.names=1,font=3,names=c("I. purpurea-S. melongena","I. aquatica-C. annuum","I. purpurea-E. sativa","I. aquatica-S. alba"))
abline(v=50,col="black")
legend(-1,-0.5,legend=c("Recipient","Donor"),bty="n",fill = coul)
text(9,3.5,"B) Convolvulaceae")

ratio_sol <-readRDS("Rmd/Data/ratio_sol.RData")
barplot(ratio_sol,hor=T, xlim=c(-1,100),ylim=c(-2,7),width = 0.5,col=coul ,space=0.5,border="white",srt=80,las=1,cex.axis=1,cex.names=1,font=3,names=c("C. annuum-I. purpurea", "S. melongena-I. aquatica", "P. integrifolia-I. aquatica", "S. lycopersicum-I aquatica","S. melongena-E. sativa", "P. integrifolia-E. sativa", "C. annuum-S. alba", "S. lycopersicum-B. rapa"))
abline(v=50,col="black")
legend(-1,-0.1,legend=c("Recipient","Donor"),bty="n",fill = coul)
text(6.8,6.8,"C) Solanaceae")

```

\newpage

```{r, echo=FALSE, message=FALSE, warning=FALSE,cache=FALSE,fig.height=9,fig.width=7}
library(ggplot2)
total_pollen <- read.csv("Rmd/Data/total_pollen.csv")
ggplot(total_pollen, aes(x=spp, y=ratio, fill=variable,width=.9)) +
  geom_bar(stat='identity', position='dodge')+theme_minimal()+
  theme(legend.title = element_blank(),axis.text.x=element_text(angle=60,hjust=1,face="italic"))+
  scale_fill_manual(values=c("#999999","#779799"),labels = c("Recipient","Donor"))+labs(x = "",y="Pollen on stigma")

```

