---
title: "Untitled"
output:
  pdf_document: default
  html_document: default
---
```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE}
library(kableExtra)
load("Data/Table_s4.RData")

r <- c(selfing[3], pollen_size[3], mean_pollen_anther[3], mean_ovules[3], pollen_ovule_ratio[3], stigma_area[3], stigma_length[3], stigma_width[3], style_length[3], style_width[3], ovary_length[3], ovary_width[3], si_index[3])
r<- as.numeric(r)
p <- c(selfing[4], pollen_size[4], mean_pollen_anther[4], mean_ovules[4], pollen_ovule_ratio[4], stigma_area[4], stigma_length[4], stigma_width[4], style_length[4], style_width[4], ovary_length[4], ovary_width[4],si_index[4])
p <- as.numeric(p)
trait <- c("Selfing rate", "Pollen size", "Pollen per anther", "Number of ovules", "**Pollen-ovule ratio**", "Stigmatic area", "Stigma length", "Stigma width", "Style length", "Style width","Ovary length","Ovary width", "Self-incompatibility index")

table<- data.frame(r,p, trait)
colnames(table) <- c("Mantel statistic", "Significance", "Traits")
kable(table, format="markdown", digits = 2)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE}
library(kableExtra)
load("Data/Table_s5.RData")

r <- c(selfing_soly[3], pollen_size_soly[3], mean_pollen_anther_soly[3], mean_ovules_soly[3], pollen_ovule_ratio_soly[3], stigma_area_soly[3], stigma_length_soly[3], stigma_width_soly[3], style_length_soly[3], style_width_soly[3], ovary_length_soly[3], ovary_width_soly[3], si_index_soly[3],selfing_bras[3], pollen_size_bras[3], mean_pollen_anther_bras[3], mean_ovules_bras[3], pollen_ovule_ratio_bras[3], stigma_area_bras[3], stigma_length_bras[3], stigma_width_bras[3], style_length_bras[3], style_width_bras[3], ovary_length_bras[3], ovary_width_bras[3], si_index_bras[3])
r<- as.numeric(r)
p <- c(selfing_soly[4], pollen_size_soly[4], mean_pollen_anther_soly[4], mean_ovules_soly[4], pollen_ovule_ratio_soly[4], stigma_area_soly[4], stigma_length_soly[4], stigma_width_soly[4], style_length_soly[4], style_width_soly[4], ovary_length_soly[4], ovary_width_soly[4],si_index_soly[4],selfing_bras[4], pollen_size_bras[4], mean_pollen_anther_bras[4], mean_ovules_bras[4], pollen_ovule_ratio_bras[4], stigma_area_bras[4], stigma_length_bras[4], stigma_width_bras[4], style_length_bras[4], style_width_bras[4], ovary_length_bras[4], ovary_width_bras[4],si_index_bras[4])
p <- as.numeric(p)
trait <- c("Selfing rate", "Pollen size", "Pollen per anther", "Number of ovules", "Pollen-ovule ratio", "Stigmatic area", "Stigma length", "Stigma width", "Style length", "Style width","Ovary length","Ovary width", "**Self-incompatibility index**","Selfing rate", "Pollen size", "Pollen per anther", "Number of ovules", "Pollen-ovule ratio", "Stigmatic area", "Stigma length", "Stigma width", "Style length", "Style width","Ovary length","Ovary width", "Self-incompatibility index")

Family <- c(rep("Solanaceae", 13), rep("Brassicaceae", 13))  

table<- data.frame(r,p, trait, Family)
colnames(table) <- c("Mantel statistic", "Significance", "Traits", "Family")
kable(table, format="markdown", digits = 2)
```

