---
output:
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    toc: no
  html_document:
    toc: no
    df_print: paged
fontsize: 12pt
header-includes:
- \usepackage{setspace}\doublespacing
- \usepackage{float}
- \usepackage{caption}

---
\captionsetup[figure]{labelformat=empty}
\captionsetup[table]{labelformat=empty}
\renewcommand{\figurename}{}


```{r, echo=FALSE, message=FALSE, warning=FALSE,cache=FALSE,fig.height=6,fig.width=12,  fig.cap="**Fig. S7** Violin plot of the proportion of seeds coverted to ovule (%) for all species with four different hand-pollination treatments: apomixis (orange), hand cross pollination (green), hand self pollination (blue) and spontaneous selfing (yellow). The coloured dots, represent the different values of seed:ovule ratio for each treatment."}

setwd("~/R_projects/Hp_pollen_experiment")


#Script to plot the reproductive biology tests
#load libraries
library(ggplot2)
#install.packages("devtools")
library(devtools)
#install_github("easyGgplot2", "kassambara")
library(effsize)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(cowplot)
library(gridExtra)
library(egg)
library(magrittr)
library(multipanelfigure)
library(grid)

brol <- read.csv("Raw_data/brol_seed_set_final.csv")
brra <- read.csv("Raw_data/brra_seed_set_final.csv")
ersa <- read.csv("Raw_data/ersa_seed_set_final.csv")
sial <- read.csv("Raw_data/sial_seed_set_final.csv")
ipaq <- read.csv("Raw_data/ipaq_seed_set_final.csv")
ippu <- read.csv("Raw_data/ippu_seed_set_final.csv")
caan <- read.csv("Raw_data/caan_seed_set_final.csv")
pein <- read.csv("Raw_data/pein_seed_set_final.csv")
soly <- read.csv("Raw_data/soly_seed_set_final.csv")
some <- read.csv("Raw_data/some_seed_set_final.csv")
#loading traits to divide by number of ovules the seed set 
traits <- read.csv("Data/Csv/traits_scinames.csv")


brol_r <- subset(brol, Treatment=="Cross"|Treatment=="Self"|Treatment=="Control"|Treatment=="FC")
brol_r$Seed_set <- brol_r$Seed.production/traits[1,8]*100
brra_r <- subset(brra, Treatment=="Cross"|Treatment=="Self"|Treatment=="Control"|Treatment=="Flower Control")
brra_r$Seed_set <- brra_r$Seed.production/traits[2,8]*100
ersa_r <- subset(ersa, Treatment=="Cross"|Treatment=="Self"|Treatment=="Control"|Treatment=="Flower Control")
ersa_r$Seed_set <- ersa_r$Seed.production/traits[4,8]*100
sial_r <- subset(sial, Treatment=="Cross"|Treatment=="Self"|Treatment=="Control"|Treatment=="Flower Control")
sial_r$Seed_set <- sial_r$Seed.production/traits[8,8]*100
ipaq_r <- subset(ipaq, Treatment=="Cross"|Treatment=="Self"|Treatment=="Control"|Treatment=="Flower control")
ipaq_r$Seed_set <- ipaq_r$Seed.production/traits[5,8]*100
ippu_r <- subset(ippu, Treatment=="Cross"|Treatment=="Self"|Treatment=="Control"|Treatment=="Flower control")
ippu_r$Seed_set <- ippu_r$Seed.production/traits[6,8]*100
caan_r <- subset(caan, Treatment=="CROSS"|Treatment=="SELF"|Treatment=="CONTROL"|Treatment=="FLOWER CONTROL")
caan_r$Seed_set <- caan_r$Seed.production/traits[3,8]*100
pein_r <- subset(pein, Treatment=="CROSS"|Treatment=="SELF"|Treatment=="CONTROL"|Treatment=="FLOWER CONTROL")
pein_r$Seed_set <- pein_r$Seed.production/traits[7,8]*100
soly_r <- subset(soly, Treatment=="Cross"|Treatment=="Self"|Treatment=="Control"|Treatment=="Flower control")
soly_r$Seed_set <- soly_r$Seed.production/traits[9,8]*100
some_r <- subset(some, Treatment=="Cross"|Treatment=="Self"|Treatment=="Control"|Treatment=="Flower control")
some_r$Seed_set <- some_r$Seed.production/traits[10,8]*100

d <- rbind(brol_r,brra_r,ersa_r,sial_r,ipaq_r,ippu_r,caan_r,pein_r,soly_r,some_r)
d$Seed_set[d$Seed_set>100]<-100

#levels(d$Treatment)
d$Treatment=as.character(d$Treatment)
d$Treatment[d$Treatment=="Cross"]<-"Hand cross-pollination"
d$Treatment[d$Treatment=="CROSS"]<-"Hand cross-pollination"
d$Treatment[d$Treatment=="Self"]<-"Hand self-pollination"
d$Treatment[d$Treatment=="SELF"]<-"Hand self-pollination"
d$Treatment[d$Treatment=="SELF"]<-"Hand self-pollination"
d$Treatment[d$Treatment=="Control"]<-"Apomixis"
d$Treatment[d$Treatment=="CONTROL"]<-"Apomixis"
d$Treatment[d$Treatment=="FC"]<-"Spontaneous selfing"
d$Treatment[d$Treatment=="Flower control"]<-"Spontaneous selfing"
d$Treatment[d$Treatment=="FLOWER CONTROL"]<-"Spontaneous selfing"
d$Treatment[d$Treatment=="Flower Control"]<-"Spontaneous selfing"

d$Species=as.character(d$Species)
d$Species[d$Family=="BROL"]<-"B"
d$Species[d$Family=="BRRA"]<-"B"
d$Species[d$Family=="ERSA"]<-"B"
d$Species[d$Family=="SIAL"]<-"B"
d$Species[d$Family=="IPPU"]<-"C"
d$Species[d$Family=="IPAQ"]<-"C"
d$Species[d$Family=="SOME"]<-"S"
d$Species[d$Family=="SOLY"]<-"S"
d$Species[d$Family=="PEIN"]<-"S"
d$Species[d$Family=="CAAN"]<-"S"

d$Species[d$Species=="BROL"]<-"B. oleracea"
d$Species[d$Species=="BRRA"]<-"B. rapa"
d$Species[d$Species=="SIAL"]<-"S. alba"
d$Species[d$Species=="ERSA"]<-"E. sativa"
d$Species[d$Species=="IPPU"]<-"I. purpurea"
d$Species[d$Species=="IPAQ"]<-"I. aquatica"
d$Species[d$Species=="SOLY"]<-"S. lycopersicum"
d$Species[d$Species=="SOME"]<-"S. melongena"
d$Species[d$Species=="PEIN"]<-"P. integrifolia"
d$Species[d$Species=="CAAN"]<-"C. annuum"

cbPalette <- c( "#56B4E9","#E69F00", "#999999", "#009E73")

 ggplot(d, aes(x=Species, y=Seed_set, fill=Treatment)) + 
  geom_violin(scale = "width",draw_quantiles = c(0.5))+
  geom_dotplot(binaxis='y', 
               dotsize=0.15,stackdir='center',position = position_jitterdodge(jitter.width = 0.01))+
  theme_minimal()+labs(y="Seed:ovule ratio")+scale_fill_manual(name="Treatments",values=c( "#D55E00","#009E73","#0072B2", "#E69F00"))+theme(plot.title = element_text(face = "bold"),axis.text.x = element_text(face = "italic"))